### ISSUE TITLE
We need debug symbols for iOS Release builds

### ISSUE THREAD

**Issue by orangemocha** [thaliproject/jxcore#103]
iOS builds (which with the current scripts can only be made in Release flavor) lack debug symbols. This is problematic because when we get a crash report we have very little information to help us find the cause.

In the current scripts, debugging symbols are never generated. [This setting](https://github.com/thaliproject/jxcore/blob/2d4a3dd87038863eee73f8bc9f5c69873644da91/common.gypi#L306) controls that.

Ideally, symbols would be generated for all build flavors and saved as separate (dSYM) files for release builds. We would package them by default in our test builds, but exclude them from the final "golden" releases.

**Comment by orangemocha** [comment]
To the best of my knowledge, with clang/gcc this would be accomplished by always generating debug symbols (passing `-g` to the compiler, i.e. changing [this setting](https://github.com/thaliproject/jxcore/blob/2d4a3dd87038863eee73f8bc9f5c69873644da91/common.gypi#L306) to `YES`), and then stripping them into separate .dSYM files. The stripping would be done as in (per http://stackoverflow.com/a/26877506):
```
dsymutil <binary> -o <binary>.dSYM
strip -S <binary>
```

I tried this approach and it works but unfortunately the stripped binary is still much larger than the binary produced with no `-g`. 

| binary | no `-g` | `-g` | `-g` + `strip` |
| --- | ---: | ---: | ---: |
 | libcares.a        |    1,049,648 |   3,291,176 |   1,894,624  |
 | libchrome_zlib.a  |    1,050,712 |   1,046,840 |   1,050,712  |
 | libhttp_parser.a  |     193,392 |    373,016 |    282,576  |
 | libjx.a           |   17,661,152 |  91,890,480 |  48,107,544  |
 | libleveldb.a      |    3874,968 |  27,612,984 |  13,105,648  |
 | libleveldown.a    |    1,519,984 |   1,509,000 |   1,519,984  |
 | libmozjs.a        |   90,870,640 |  90,475,656 |  90,870,640  |
 | libopenssl.a      |   28,719,888 |  95,144,584 |  54,767,528  |
 | libsnappy.a       |     210,400 |   1,066,432 |    539,088  |
 | libsqlite3.a      |    7,860,656 |   7,855,392 |   7,860,656  |
 | libuv.a           |    1,554,272 |   5,214,032 |   3,018,368  |

I dug into it for libjx.a, and found that while i386 and x86_64 binaries are getting stripped successfully to their no `-g` size, arm* binaries are still 3x the size of their no `-g` counterparts after stripping.

No `-g`:
```
lipo -detailed_info libjx.a 
Fat header in: libjx.a
fat_magic 0xcafebabe
nfat_arch 5
architecture armv7
    cputype CPU_TYPE_ARM
    cpusubtype CPU_SUBTYPE_ARM_V7
    offset 108
    size 4404768
    align 2^2 (4)
architecture armv7s
    cputype CPU_TYPE_ARM
    cpusubtype CPU_SUBTYPE_ARM_V7S
    offset 4404876
    size 4412952
    align 2^2 (4)
architecture i386
    cputype CPU_TYPE_I386
    cpusubtype CPU_SUBTYPE_I386_ALL
    offset 8817828
    size 2031416
    align 2^2 (4)
architecture x86_64
    cputype CPU_TYPE_X86_64
    cpusubtype CPU_SUBTYPE_X86_64_ALL
    offset 15386784
    size 2274368
    align 2^3 (8)
architecture arm64
    cputype CPU_TYPE_ARM64
    cpusubtype CPU_SUBTYPE_ARM64_ALL
    offset 10849248
    size 4537536
    align 2^3 (8)
```

`-g`:
```
lipo -detailed_info libjx.a 
Fat header in: libjx.a
fat_magic 0xcafebabe
nfat_arch 5
architecture armv7
    cputype CPU_TYPE_ARM
    cpusubtype CPU_SUBTYPE_ARM_V7
    offset 108
    size 23195344
    align 2^2 (4)
architecture armv7s
    cputype CPU_TYPE_ARM
    cpusubtype CPU_SUBTYPE_ARM_V7S
    offset 23195452
    size 23085152
    align 2^2 (4)
architecture i386
    cputype CPU_TYPE_I386
    cpusubtype CPU_SUBTYPE_I386_ALL
    offset 46280604
    size 10776832
    align 2^2 (4)
architecture x86_64
    cputype CPU_TYPE_X86_64
    cpusubtype CPU_SUBTYPE_X86_64_ALL
    offset 80585928
    size 11304552
    align 2^3 (8)
architecture arm64
    cputype CPU_TYPE_ARM64
    cpusubtype CPU_SUBTYPE_ARM64_ALL
    offset 57057440
    size 23528488
    align 2^3 (8)
```

`-g` + `strip`:
```
lipo -detailed_info libjx.a 
Fat header in: libjx.a
fat_magic 0xcafebabe
nfat_arch 5
architecture armv7
    cputype CPU_TYPE_ARM
    cpusubtype CPU_SUBTYPE_ARM_V7
    offset 108
    size 14544416
    align 2^2 (4)
architecture armv7s
    cputype CPU_TYPE_ARM
    cpusubtype CPU_SUBTYPE_ARM_V7S
    offset 14544524
    size 14552632
    align 2^2 (4)
architecture i386
    cputype CPU_TYPE_I386
    cpusubtype CPU_SUBTYPE_I386_ALL
    offset 29097156
    size 2033120
    align 2^2 (4)
architecture x86_64
    cputype CPU_TYPE_X86_64
    cpusubtype CPU_SUBTYPE_X86_64_ALL
    offset 45831928
    size 2275616
    align 2^3 (8)
architecture arm64
    cputype CPU_TYPE_ARM64
    cpusubtype CPU_SUBTYPE_ARM64_ALL
    offset 31130280
    size 14701648
    align 2^3 (8)
```

I tried a variety of `strip` options and also adding -fvisibility=hidden to the compiler switches, but without any improvement.

The next step in the investigation would be to dump the arm symbols in further detail and see what is still left in the binary, and if we can manage to strip it. If we can't get to the bottom of it, the next best option would be to modify the build scripts to be able to generate two distinct build flavors: a golden release for production, and a release with symbols for development and testing.

**Comment by enricogior** [comment]
Enabling the `GCC_GENERATE_DEBUGGING_SYMBOLS` flag in release build is an acceptable trade-off given the binaries size increases from ~155MB to ~223MB.
