### ISSUE TITLE
Test failures in iOS test app on actual devices

### ISSUE THREAD

**Issue by orangemocha** [thaliproject/jxcore#105]
Many tests (~125) fail when running the test app on actual hardware devices. This needs to be investigated. It is probably an issue with how the test app itself manipulates the temp folder.

**Comment by enricogior** [comment]
Most of the tests failing on the device were failing because they didn't have write access to the test folder (on the simulator there isn't that limitation). The fix is to move all the tests in a temp folder where the tests have write access.
After that fix there are still some tests that are failing on the device but not on the simulator:
5 test-buffer-ascii.js
187 test-fs-utimes.js
550 test-timers-unref.js

**Comment by enricogior** [comment]
Overall there are still 4 test failing:

5 test-buffer-ascii.js (fails on device only)
245 test-http-exit-delay.js (flaky, on device and on the simulator)
464 test-require-resolve.js (fails on device and on the simulator)
550 test-timers-unref.js (fails on device only)

**Comment by enricogior** [comment]
| # | Test name | iOS9 sim |  iOS9 device | iOS10 sim | iOS10 device |
| ---: | :--- | :---: | :---: | :---: | :---: |
| 5 | test-buffer-ascii.js |  | **KO** |  | **KO** |
| 109 | test-dgram-udp4.js | F-A | | F-A | |
| 155 | test-fs-empty-readStream.js | F-A | | F-A | |
| 245 | test-http-exit-delay.js | F-A | F-A | | |
| 382 | test-net-settimeout.js | | | F-S | |
| 464 | test-require-resolve.js | **KO** | **KO** | **KO** | **KO** |
| 547 | test-timers-unref-active.js | F-S | | F-S | |
| 550 | test-timers-unref.js | | **KO** | | **KO** |
| 551 | test-timers-unrefd-interval-still-fires.js| | | F-S | |

KO = 100% fail when run standalone.
F-S = is a flaky test when run standalone.
F-A = is a flaky test when run after other tests.

**Comment by enricogior** [comment]
464 test-require-resolve.js (fails on device and on the simulator) has been fixed.

**Comment by enricogior** [comment]
550 test-timers-unref.js fixed by https://github.com/thaliproject/jxcore/commit/a916b73edb13effab6bd65609bc35334a53dd981

**Comment by enricogior** [comment]
Last test that still fails on device is `test-buffer-ascii.js`, it seems a legitimate jxcore bug, not a test problem.

**Comment by enricogior** [comment]
The bug exposed by `test-buffer-ascii.js` is occuring in `contains_non_ascii()` when the input string length is >= 16 chars:
https://github.com/thaliproject/jxcore/blob/master/src/string_bytes.cc#L395

**Comment by enricogior** [comment]
test-buffer-ascii.js fixed by:
https://github.com/thaliproject/jxcore/commit/a654a6d71e2b40a4ede38dc22a51b26888b9d760

**Comment by enricogior** [comment]
All tests that were failing on the device only have been fixed.
The flaky tests are now reported in a dedicated issue https://github.com/thaliproject/jxcore/issues/110
