### ISSUE TITLE
Assert in leveldown-mobile during thali tests on iOS

### ISSUE THREAD

**Issue by orangemocha** [thaliproject/jxcore#106]
I ran into an assert when running thali tests on iOS hardware. 

An id is passed into JavaScript and back into native. On the way in, a native int32_t is marshalled to as a [JS number with STD_TO_NUMBER()](https://github.com/thaliproject/leveldown-mobile/blob/3df92aa40665b3d6098eefeb2826d07b701d3bc4/src/database.cc#L470). On the way out, the JS_LOCAL_VALUE [is accessed with Int32Value()](https://github.com/thaliproject/leveldown-mobile/blob/3df92aa40665b3d6098eefeb2826d07b701d3bc4/src/iterator.cc#L401).

This causes an assert in SpiderMonkey, because of [this code](https://github.com/thaliproject/jxcore/blob/2d4a3dd87038863eee73f8bc9f5c69873644da91/src/jx/Proxy/Mozilla_340/MozJS/MozValue.cc#L430-L431) assumes that on ARM a value represented as 'Number' 0 is really an integer, while the value was created as a Number.

```
int32_t Value::Int32Value() {
  if (empty_) return 0;

  if (value_.isNumber()) {
    int32_t xv = (int32_t)value_.toNumber();
#ifdef JS_CPU_ARM
    if (xv == 0) xv = value_.toInt32();
#endif
```

`value._toInt32()` (a SpiderMonkey API) asserts that the value must be stored as an integer. This is consistent with the [SpiderMonkey API documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_Reference/JS::Value):

> JS::Value is not inherently type-safe
> It is an error to call any accessor method on a value of a non-matching type: val.toInt32() must only be called if val.isInt32(), val.toString() must only be called if val.isString(), and so on.

One could argue that leveldown-mobile should create the JS value with STD_TO_INTEGER() rather than STD_TO_NUMBER(), however the Int32() API is a higher-level API than SpiderMonkey's toInt32() and it seems that it would be able to convert floating point numbers to int32_t on ARM as it does on other platforms, and as [the v8 API does](http://v8.paulfryzel.com/docs/master/api_8cc_source.html#l03953).

**Comment by orangemocha** [comment]
I have a fix for this.

**Comment by enricogior** [comment]
Fixed.
https://github.com/thaliproject/jxcore/commit/e43a19c2d439927de784792dd08bbabe7de0b5ca
