### ISSUE TITLE
Why do I need to have a private and public key for a PSK connection?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore#2]
We'll work around this for now but why if I just want to support PSK do I get an error saying "Missing PFX or certificate + private key."? I only want to support PSK connections, I don't want to support any certs.

**Comment by cicorias** [comment]
Its not a bug its left there as client handshake would allow non Psk

Also left as it was too disruptive to the code base I felt.

**Comment by yaronyg** [comment]
Right but it's one thing to say "you can do a cert based or PSK based handshake" it's another to say "You MUST have a cert and key even though you aren't going to use them." But such is life.  We should see this fixed in JXcore but it will stay in the icebox for now.

**Comment by cicorias** [comment]
we can bypass this check: https://github.com/thaliproject/jxcore/blob/master/lib/tls.js#L1063

As there is already a setting to provide an early conditional: 

`isPskServer`

https://github.com/thaliproject/jxcore/blob/master/lib/tls.js#L1106
https://github.com/thaliproject/jxcore/blob/master/lib/tls.js#L1199
