### ISSUE TITLE
Need to clean up skipped tests and investigating known failing ones

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore#25]
In the Node test suite there are tests that were failing with the last release of JXcore from Nubisa (e.g. we didn't make them fail) as well as a bunch of tests that are being skipped. Unfortunately the CI system used by Nubisa is very old and it doesn't output a log and it doesn't know how to count skipped versus passing tests. So we need to go investigate which tests are being skipped and see if we want to actually run them and we also need to investigate the known failures to see if we want to fix them.

**Comment by yaronyg** [comment]
Will start working tomorrow.

**Comment by yaronyg** [comment]
Working on it

**Comment by yaronyg** [comment]
Manually checked over 600 tests and found several tests that are skipped in some cases on all platforms, in some cases on windows, in some cases because of SpiderMonkey, etc. Some skips seem legitimate and some not so much. So now we can report all the skip tests and see which are skipped on which platforms.

**Comment by yaronyg** [comment]
There are only 9 tests skipped on all platforms. One is for debugging functionality, some are TLS, some are HTTPS, we will have to investigate to see why they are being skipped.

**Comment by enricogior** [comment]
PR submitted https://github.com/thaliproject/jxcore/pull/40
