### ISSUE TITLE
fix the scripts to build the debug version of iOS and Android libs

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#26]
ios_compile.sh and android_compile.sh don't accept a `--debug` flag as input parameter.
Adding the `--debug` flag in the scripts when `configure` is called doesn't work.

**Comment by yaronyg** [comment]
@enricogior I'm moving this to icebox under the assumption that this is not blocking you. If I'm wrong please move it back to Backlog and put in the note that it is, in fact, blocking you.

**Comment by enricogior** [comment]
Closing this since we are now tracking the issues here: https://github.com/thaliproject/jxcore/issues/95
