### ISSUE TITLE
disable SSLv3 and TLSv1.0

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#28]
The work consits of:
 - disabling SSLv3
 - disabling TLSv1.0
 - add test to verify SSLv3 is disabled
 - add tests to verify TSLv3 is disabled
 - modify/disable tests that currently use SSLv3
 - modify/disable tests that currently use TLSv3

**Comment by yaronyg** [comment]
Work has started.

**Comment by larryonoff** [comment]
Work is in progress. Tests to be added.

We need an external config file to set-up ciphers that we need.

**Comment by yaronyg** [comment]
Diego has finished the work and we need to review the code and then send out a PR.

**Comment by yaronyg** [comment]
There were a few issues found in the code review, Diego fixed the issues and ran the tests on Mac OS and is now running on Android and hopefully later today we'll have the PR if there are no issues with the tests.

**Comment by enricogior** [comment]
The work is completed, but we still have to clean up the commits before sending the PR.

**Comment by yaronyg** [comment]
It's finished but there are still some commits that need to be cleaned up. We need to polish the commits, do a rebase, etc. But we wanted him to start on iOS. So we are putting this on hold today and will finish it tomorrow.

**Comment by enricogior** [comment]
The code is complete, but there are three tests that are now failing if the system's OpenSSL is not updated. The tests need to be changed to verify the system's OpenSSL version and skip the test if it doesn't meet the minimum requirements.

**Comment by yaronyg** [comment]
There are three tests that require a specific version or higher of OpenSSL but Travis has an older version and so we need to put in some logic to turn off those tests when the required version isn't available. We had other blocking issues today so we'll get to this next week.

**Comment by enricogior** [comment]
Found a problem with the logic used by some tests to verify if the system's OpenSSL version is 1.0.0 or greater. Some tests were skipped erroneously, the fix is simple but it takes time and we have more urgent issues.

The code that doesn't work is like this one:
```
function checkOpenSSL() {
  exec('openssl version', function(err, data) {;
    if (err) throw err;
    if (/OpenSSL 0\./.test(data)) {
      console.error('Skipping due to old OpenSSL version.');
      return false;
    }
    else {
      return true;
    }
  });
}

if (! checkOpenSSL()){
  console.error("Skipping because OpenSSL version < 1.0.0.");
  process.exit(0)
}
```
checkOpenSSL() always returns true, since is not returning the result of the 'exec' command.

**Comment by yaronyg** [comment]
I created https://github.com/thaliproject/jxcore/issues/58 to track this issue.

**Comment by enricogior** [comment]
After fixing test-tls-psk-Client.js, that has never been run because of a bug in the test itself, a new bug in the negotiation between the client and the server in the SSL23_client_method() has been found.
Still investigating the problem.
After that issue will be fixed, there will be at least another day to test all the platforms (we will also run the ThaliTest app with the update jxcore-cordova plug-in if required).

**Comment by enricogior** [comment]
Found and fixed a bug in the PSK client-server negotiation.
Now verifying the other PSK tests to make sure they all work properly.

**Comment by enricogior** [comment]
Verified that all the tls-psk tests are OK.
