### ISSUE TITLE
improve scripts to automate the release process

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#29]
We currently have a set of scripts to build all the components needed to do a jxcore release but is still not a fully automated environment.
We need script(s) for jxcore-cordova too.

**Comment by yaronyg** [comment]
This should be done tomorrow morning.

**Comment by yaronyg** [comment]
Didn't work on it today.

**Comment by enricogior** [comment]
PR submitted https://github.com/thaliproject/jxbuild/pull/1
