### ISSUE TITLE
Create 3.1.4 jxcore and jxcore-cordova release.

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#32]
Build and upload the jxcore and jxcore-cordova bits.

**Comment by yaronyg** [comment]
This should be done today.

**Comment by enricogior** [comment]
jxcore binaries:
https://jxcore.blob.core.windows.net/jxcore-release/jxcore/0314/release/jx_androidFATsm.zip
https://jxcore.blob.core.windows.net/jxcore-release/jxcore/0314/release/jx_iosFATsm.zip
https://jxcore.blob.core.windows.net/jxcore-release/jxcore/0314/release/jx_osx64sm.zip
https://jxcore.blob.core.windows.net/jxcore-release/jxcore/0314/release/jx_osx64v8.zip
https://jxcore.blob.core.windows.net/jxcore-release/jxcore/0314/release/jx_win64v8.zip

jxcore-cordova binaries:
https://jxcore.blob.core.windows.net/jxcore-release/jxcore-cordova/0.1.4/release/io.jxcore.node.jx

npmjx binaries:
https://jxcore.blob.core.windows.net/jxcore-release/npmjx/npmjx314.tar.gz
https://jxcore.blob.core.windows.net/jxcore-release/npmjx/npmjxv314.jx

**Comment by enricogior** [comment]
Updated https://github.com/thaliproject/jxbuild/blob/master/distribute.md with download links.

**Comment by enricogior** [comment]
Created PRs to merge release branches into master branches:
https://github.com/thaliproject/jxcore/pull/33
https://github.com/thaliproject/jxcore-cordova/pull/8
