### ISSUE TITLE
Travis should use latest XCode version

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#36]
This is a sub task of https://github.com/thaliproject/jxcore/issues/16

I've tried to update trevis.xml to use the latest XCode version previously, but it was failing because the log size exceeded the max length, the solution maybe to redirect the stderr and/or the stdout to a log file. I need to verify if we can later access the log file for investigation if needed.

**Comment by yaronyg** [comment]
Right now it's using Xcode 6 and 7 and that means we need 2x time to run which is silly so we need to turn of 6 but we don't yet know how.

**Comment by enricogior** [comment]
Things are not looking good at all with Travis and XCode 7.3.

The [first build failed](https://travis-ci.org/thaliproject/jxcore/builds/156522615) after 40 minutes because of tests failure with jxcore V8:
`[03:48|% 100|+ 633|-   3]: Done`

The [second build failed](https://travis-ci.org/thaliproject/jxcore/builds/156540338) after 1h27m because of tests failure with both jxcore V8 and SM:
`[03:00|% 100|+ 633|-   3]: Done`
`[04:49|% 100|+ 634|-   2]: Done`

The [third build failed](https://travis-ci.org/thaliproject/jxcore/builds/156599234) after 41 minutes because of tests failure with jxcore V8:
`[02:57|% 100|+ 634|-   2]: Done`

By default Travis uses XCode 6.1 on OS X 10.9 and in that case it takes 20m to build and run the tests successfully. 
So there are two issues with Travis and XCode 7.3:
 - the unjustified long time to compile.
 - the random tests failure that we never experience when using XCode 7.3 on our dev machines.

**Comment by yaronyg** [comment]
We will experiment with other services since we really don't want to debug Travis. Maybe run it with Jenkins on a mac mini?

**Comment by enricogior** [comment]
I've opened a new issue to track the specific work of finding an alternative.
https://github.com/thaliproject/jxcore/issues/43
