### ISSUE TITLE
OSX undefined char16_t

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/jxcore#46]
1. Download [install script](https://gist.github.com/andrew-aladev/098ac174192b42af216dcbf7927f51a4).
1. rm -r ~/.jx && rm -r ~/.npm && rm -r ~/.node-gyp && etc
2. ./jxcore-install.sh --force sm
3. jx install
4. cd temp
5. jx npm install fs-ext

```
Target arch x64
 CXX(target) Debug/obj.target/fs-ext/fs-ext.o
In file included from ../fs-ext.cc:20:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/node.h:46:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/jx/Proxy/JSEngine.h:51:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/jx/Proxy/Mozilla_340/JXString.h:19:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/jx/Proxy/Mozilla_340/MozJS/MozJS.h:6:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/jx/Proxy/Mozilla_340/MozJS/Isolate.h:17:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/jsapi.h:12:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/mozilla/FloatingPoint.h:12:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/mozilla/Assertions.h:16:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/mozilla/Attributes.h:12:
In file included from /Users/hiqouser/.node-gyp/jxb311/src/mozilla/Compiler.h:12:
/Users/hiqouser/.node-gyp/jxb311/src/mozilla/Char16.h:173:15: error: unknown type name 'char16_t'
typedef const char16_t* char16ptr_t;
```

I am not familiar with osx. It looks like it is using custom apple clang version. I am not sure but it looks like this clang doesn't want to support `char16_t`

**Comment by enricogior** [comment]
C++11 introduces a char16_t type and support for UTF-16 string and character literals. C++11's char16_t is a distinct builtin type.
When building 'fs-ext', node-gyp generates a makefile that doesn't set the appropriate compilation flags. 
The fix may require to update our version of node-gyp.

**Comment by yaronyg** [comment]
This is an issue that you install with jxcore a native module and i you use v8 it compiles just fine and if you use Spidermonkey it includes some Mozilla header files that defined char_16_t type that the clan compiler doesn't recognize. This problem needs to be fixed through node-gyp. node-gyp generates the make file that generations fs-ext module so the file is correct.

The real issue here is that fs-ext uses native code which depends on the v8 interfaces and isn't going to ever work with Spidermonkey so we have to figure out how to do what we are doing without using this module.

I am assigning this to @andrew-aladev and we need to discuss why we need this dependency because it isn't going to work in SpiderMonkey.

**Comment by andrew-aladev** [comment]
Let me provide more information about my steps. I've just created a [pull request](https://github.com/thaliproject/Thali_CordovaPlugin/pull/998) in my branch. I have tested it with v8.
So now I will try to install jxcore with spider monkey for this branch.

```
killall sinopia
cd
rm -r .jx*
rm -r .node-gyp/
rm -r .npm*
rm -r node_modules
./temp/jxcore-install.sh --force sm
jx install
(in new screen's window) sinopia
```

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
dyld: lazy symbol binding failed: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /usr/local/lib/node_modules/sinopia/node_modules/bunyan/node_modules/dtrace-provider/build/Debug/DTraceProviderBindings.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /usr/local/lib/node_modules/sinopia/node_modules/bunyan/node_modules/dtrace-provider/build/Debug/DTraceProviderBindings.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

```
jx npm remove -g sinopia
jx npm install -g sinopia
```

```
> CXX(target) Debug/obj.target/crypt3/crypt3.o
In file included from ../crypt3.cc:3:
...
/Users/hiqouser/.node-gyp/jxb311/src/mozilla/Char16.h:173:15: error: unknown type name 'char16_t'
```

```
> CXX(target) Debug/obj.target/fs-ext/fs-ext.o
In file included from ../fs-ext.cc:20:
...
/Users/hiqouser/.node-gyp/jxb311/src/mozilla/Char16.h:173:15: error: unknown type name 'char16_t'
```

So sinopia is not installable with jxcore and spider monkey.

```
jx npm remove -g sinopia
NVM_NODEJS_ORG_MIRROR="" npm install -g sinopia
```

```
> CXX(target) Release/obj.target/fs-ext/fs-ext.o
In file included from ../fs-ext.cc:27:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
```

This is not compatiable with latest node, lets downgrade.

```
brew unlink node
brew tap homebrew/versions
brew install homebrew/versions/node012
NVM_NODEJS_ORG_MIRROR="" npm remove -g sinopia
NVM_NODEJS_ORG_MIRROR="" npm install -g sinopia
sinopia

(in old screen's window) 
jx npm config set registry http://localhost:4873
jx npm login
cd workspace/vNext_aaladev_968/
rm -r thali/node_modules/
rm -r test/www/jxcore/node_modules/
rm -r thali/install/node_modules/
rm -r test/TestServer/node_modules/
./build.sh
```

And it works.

**Comment by yaronyg** [comment]
The key here is that certain programs like Sinopia are not compatible with SM and that is o.k. We won't ever run Sinopia on a device. We also won't ever run Sinopia in production. We only run it for testing and building. So it's fine to run it in normal Node.

**Comment by andrew-aladev** [comment]
BTW our test server depends on old "socket.io": "1.3.6". This version depends on "bufferutil" and other packages that couldn't be installed with jx. The latest "1.4.8" version has no such problem.

**Comment by yaronyg** [comment]
@andrew-aladev This bug is closed. I'll open a new one to cover this fix.
