### ISSUE TITLE
We got 'sigfault' on some android devices

### ISSUE THREAD

**Issue by artemjackson** [thaliproject/jxcore#51]
Please, see the [log](https://raw.githubusercontent.com/ThaliTester/TestResults/846186378976bee_Returned_setImmediate_workaround_artemjackson/thali03_samsung-SM-A300FU.md) from samsung-SM-A300FU and search for `Fatal signal 11`.

You can also check the logs from some other devices that failed with  `Fatal signal 11`:
[samsung-SM-A500FU](https://raw.githubusercontent.com/ThaliTester/TestResults/846186378976bee_Returned_setImmediate_workaround_artemjackson/thali03_samsung-SM-A500FU.md)
[samsung-SM-G935F](https://raw.githubusercontent.com/ThaliTester/TestResults/846186378976bee_Returned_setImmediate_workaround_artemjackson/thali05_samsung-SM-G935F.md)

**Comment by artemjackson** [comment]
1. jxcore-codova version was 0.1.4
2. The test [`# 15. #_doImmediateSeqUpdate - create new seq doc`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/8976bee9bf030803325b3bc9c5e433c1f7bbe605/test/www/jxcore/bv_tests/testLocalSeqManager.js#L134) caused the crash

**Comment by enricogior** [comment]
Code from: https://github.com/thaliproject/Thali_CordovaPlugin/blob/8976bee9bf030803325b3bc9c5e433c1f7bbe605/test/www/jxcore/bv_tests/testLocalSeqManager.js#L134
The test has been run only once so at the moment it's unknown if it's failing consistently or not.

**Comment by artemjackson** [comment]
The issue occurred only on 3 of 7 Android devices (SM-F300FU, SM-500FU, SM-G935F). All of them run Android 6.0.1.
So I think you can just get any of these devices and reproduce the crash.
I think you can run individual test, but Thali tests are really deep connected, so sometimes bugs can be reproduced only with full test suite

**Comment by enricogior** [comment]
I've run the bv_tests 5 times using the code from branch vNext_artemjackson_417_812_fixes and using two devices SM-G935F and SM-G925F. The bug never repro'd.

**Comment by yaronyg** [comment]
@chapko Please add a note here about the bug you ran into.

**Comment by chapko** [comment]
I've got the same segfault on CI in thaliproject/Thali_CordovaPlugin#1180 PR.
Both test runs are failed on Samsung devices before devices are connected to the coordination server. Right now it is reproducible in [`043b018`](https://github.com/thaliproject/Thali_CordovaPlugin/commit/043b018ba4a95448f31028bf83be08c3040bdebb) commit and [here are logs from CI](https://github.com/ThaliTester/TestResults/tree/86918701043b018_fix__1059_chapko/)

**Comment by evabishchevich** [comment]
Enrico, there are  some logs related to that issue
https://raw.githubusercontent.com/ThaliTester/TestResults/86930490b689f01_Android_changes_to_superbranch_evabishchevich/thali05_samsung-SM-G930F.md
https://raw.githubusercontent.com/ThaliTester/TestResults/86930490b689f01_Android_changes_to_superbranch_evabishchevich/thali05_samsung-SM-G935F.md

**Comment by enricogior** [comment]
Using latest jxcore-cordova 0.1.5 and tests from master I can't repro this.
