### ISSUE TITLE
Is this causing us to crash or the result of a bad TCP/IP connection failure?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore#69]
2016-10-24 13:05:26 - DEBUG thaliReplicationPeerAction: 'Got error on replication -  500 3663681840:error:1408E0F4:SSL routines:SSL3_GET_MESSAGE:unexpected message:../deps/openssl/openssl/ssl/s3_both.c:477:

**Comment by enricogior** [comment]
The error is handled by openssl, it doesn't cause a crash in jxcore.
It may be similar to https://github.com/thaliproject/Thali_CordovaPlugin/issues/1406 where we verified that the error is caused by a bad request: the data corruption has already occurred when the packet is received, therefore the instance of jxcore that is handling the packet is just reporting the error.

**Comment by yaronyg** [comment]
Can this bug happen if a message just stops sending data, some kind of time out or would this only occur if actually bad data is received?

**Comment by enricogior** [comment]
@yaronyg is this happening over WiFi or over BT?

**Comment by yaronyg** [comment]
BT

**Comment by yaronyg** [comment]
Repro:

https://github.com/thaliproject/ThaliTestApp/tree/aaladev_1407 - Use this branch to run the test app
https://github.com/thaliproject/thali_cordovaplugin/tree/master_yarong_1446 - This branch for Thali
Make sure to read the readme for ThaliTestApp, it tells you how to safely start things. You want to choose Bluetooth.

**Comment by chapko** [comment]
Here are logs (unfortunately I have only filtered version):
- [1.log](https://gist.github.com/chapko/3e52a6e586cf7976e2c8900caa7e4d8e/raw/e0fd80594a7b89882e9b69386f4157e370423e14/1.log)
- [2.log](https://gist.github.com/chapko/3e52a6e586cf7976e2c8900caa7e4d8e/raw/e0fd80594a7b89882e9b69386f4157e370423e14/2.log)

I was running ThaliTestApp `aaladev_1407` branch (thaliproject/ThaliTestApp@5ba863115f0b28a76c793829bcbcd8d1c8ac99fa) with thali `master_yarong_1446` branch (thaliproject/Thali_CordovaPlugin@4264c94d4c97d8137ba775d457d719abcc074344)

**Comment by chapko** [comment]
Also I see the same error on desktop (with v8 version of jx)

**Comment by enricogior** [comment]
@chapko can you please confirm the repro step when using ThaliTestApp?
On desktop with V8 what tests are you running?
Thanks.

**Comment by chapko** [comment]
In the ThaliTestApp there is a [runOnDesktop.js](https://github.com/thaliproject/ThaliTestApp/blob/aaladev_1407/www/jxcore/runOnDesktop.js) file. It uses wifiBasedNativeMock from main thali repo.

And then I just run 2 instances in background:
```
jx runOnDesktop.js 1 native &> logs/thali-1.log &
jx runOnDesktop.js 2 native &> logs/thali-2.log &
```

**Comment by chapko** [comment]
Turns out it is an issue in a mux layer. Replacing `.end` calls with `.destroy` on node streams fixes this SSL error on both desktop and devices.

**Comment by yaronyg** [comment]
We apparently only repo'ing this so I'm going to close. We can (sadly) open it again if it comes back.
