### ISSUE TITLE
Make sure that Thali's JXcore and mainline JXcore are the same

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore#7]
Did we get all of our changes accepted to JXcore?

**Comment by enricogior** [comment]
@yaronyg 
I've compared the master branches from jxcore/jxcore and thaliproject/jxcore.
There is one commit in jxcore/jxcore that is not present in thaliproject/jxcore:
https://github.com/jxcore/jxcore/commit/f047c10f9cf521a43b6ffe4ea58fd27a3267f205
and viceversa the is one commit in thaliproject/jxcore that is not present in jxcore/jxcore
https://github.com/thaliproject/jxcore/commit/1c214d84d2459e63926b3e6f8da395dba852d8ab

**Comment by yaronyg** [comment]
So why don't you submit https://github.com/thaliproject/jxcore/commit/1c214d84d2459e63926b3e6f8da395dba852d8ab as your first PR to JXcore and then once that is accepted we can do a new full build?

**Comment by enricogior** [comment]
Sure.

**Comment by enricogior** [comment]
PR created https://github.com/jxcore/jxcore/pull/901
I'm not closing this issue yet, since the PR is the first half of the work, the second part is to merge changes from mainline jxcore.

**Comment by enricogior** [comment]
https://github.com/thaliproject/jxcore/commit/4ff50aaccd21adeeeb6f669e7171415f3866e5d2

**Comment by yaronyg** [comment]
There are changes we have that aren't in mainline but we aren't completely sure what they are doing. So Enrico will ask Shawn about the changes and clean things up.

**Comment by yaronyg** [comment]
Waiting for a email response from Shawn

**Comment by yaronyg** [comment]
Enrico talked with Shawn to understand the code and he will submit a PR.

**Comment by enricogior** [comment]
PR created for ["allowing no pfx/cert on psk"](https://github.com/jxcore/jxcore/pull/903).
Keeping the issue open since it's a work in progress and more PRs will be made.

**Comment by yaronyg** [comment]
The fixes in this are already in our release of JXcore but this bug is about submitting the changes to the main JXcore depot.

**Comment by yaronyg** [comment]
At this point we have everything in JXcore but there are a few things we have that aren't in JXcore yet so we have to submit those. It's all minor stuff.

**Comment by enricogior** [comment]
PR submitted to mainline jxcore:
https://github.com/jxcore/jxcore/pull/906
https://github.com/jxcore/jxcore/pull/907
https://github.com/jxcore/jxcore/pull/908
https://github.com/jxcore/jxcore/pull/909

I added issue ['#42 externalized paths change not pushed to mainline jxcore'](https://github.com/thaliproject/jxcore/issues/42) to keep track of the commits that haven't been pushed because they would cause conflicts when merging back from mainline jxcore.
