### ISSUE TITLE
Does the back button break JXcore?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore#70]
One more issue to look at. I thought this is Stanton related but I can repro it in ThaliTestApp. Steps:

1. Run ThaliTestApp. Wait until DEVICE IS READY is shown.

2. Press "Back" button on device (important: Back, not Home).

3. Enter again ThaliTestApp.

Result: jxcore is not loaded (deviceready event is received).

Logs: https://gist.github.com/czyzm/f07bd746603bbff70bbe841ee3575e22

**Comment by enricogior** [comment]
When pressing the back button, the app goes to the background, but the jxcore instance is still up and running. I've added to `app.js` the following loop:
```
function looping() {
  console.log('jxcore looping');
  setTimeout(looping, 2500);
}
looping();
```
The loop keeps running even while the app is in the background.
When the app is restored to the foreground, the loop is still running, but the cordova script `js/index.js` is in a reset state, so all variables are reset and same for the html page: for example if 'WiFi' was selected before pressing the back button, now 'Native' is selected.
It is also worthy noticing that the first time the back button is pressed and the app is restored, the `deviceready` event is received, but not the following times the app is sent to background and restored.

I don't think this is a jxcore bug, it's a problem with how the cordova app manages its state going in and out of the background.
