### ISSUE TITLE
setTimeout hangs with float timeout

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/jxcore#77]
I couldn't reproduce this on desktop with spider monkey. Please use mobile phone.

We can just add a peace of code at the end of `www/jxcore/app.js` in [Thali Test App](https://github.com/thaliproject/ThaliTestApp) and run it on mobile phone.

```
function fit (timeout) {
  var start = new Date();
  console.log('starting timeout: %d', timeout);
  setTimeout(function () {
    console.log('finished with timeout: %d, real timeout: %d', timeout, new Date() - start);
    fit(timeout);
  }, timeout);
}
fit(250 / 3);

setInterval(function () {
  console.log('process is alive');
}, 5000);
```

We can see `starting/finished` 0-200 times and than one `starting` without `finished`. Process said that it is alive.

I think we need to round our number automatically in jxcore.

**Comment by yaronyg** [comment]
When this is fixed we need to do a new release of JXcore and JXcore-Cordova

**Comment by enricogior** [comment]
https://github.com/thaliproject/jxcore/blob/master/lib/timers.js#L210

I guess setInterval has the same issue.
