### ISSUE TITLE
Externalize the paths

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore#8]
Right now we hardcode in paths pointing to our distribution points during the build. That would be what is known as 'bad'. :) We need to submit a PR to JXcore that lets us set the paths in some kind of external configuration file so that different people who download JXcore can choose to point at whatever location they want. I found at least three files in JXcore forexample that point directly at azureedge.net. But that is an endpoint owned by Microsoft. It's not something that should be in the general JXcore repo. Instead those values should point at configuration files that someone building JXcore can set up and then do a compile and produce an output that points where ever they want.

By externalizing this we can keep the JXcore build agonist from Microsoft which is what we want. We are absolutely NOT promising the world to host JXcore! :)

**Comment by enricogior** [comment]
First hardcoded path I run into while working on https://github.com/thaliproject/Thali_CordovaPlugin/issues/763 is in this script:
https://github.com/jxcore/jxcore/blob/master/tools/npmjx/index.js at line 199 contains:
```
https://jxcore.azureedge.net/npmjx/npmjx311.tar.gz
```
while https://github.com/jxcore/jxcore/blob/master/tools/npmjx/index.js contains:
```
https://s3.amazonaws.com/nodejx/npmjx311.tar.gz
```
(btw, that returns an AccessDenied error).
The url will be externalized in a config file and/or a command switch.

**Comment by enricogior** [comment]
There is also https://github.com/thaliproject/jxcore/blob/master/lib/jx/_jx_install.js that contains hardcoded strings:
```
128.   var npm_basename = 'npmjxv311.jx';
129.   var npm_str = 'https://jxcore.azureedge.net/npmjx/' + npm_basename;
```
_jx_install.js in turn calls npmjx/index.js.

**Comment by enricogior** [comment]
The solution consists of: 
 - source files that contain hard-coded URLs are replaced by templates containing URL_IDs.
 - one global configuration file to store the URL_IDs and theirs values.
 - script(s) invoked during the build process to create the source files from the templates.

**Comment by enricogior** [comment]
PR submitted.
https://github.com/thaliproject/jxcore/pull/17
