### ISSUE TITLE
Libuv:  port to fd mapping bug

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#87]
The following code:
https://github.com/thaliproject/jxcore/blob/master/deps/uv/src/unix/tcp.c#L202-L219

overwrites a valid `fd` when called in second instance of the engine after the first instance used the same port with a different `fd` associated with it.

**Comment by yaronyg** [comment]
In an ideal world we wouldn't do anything that would require a perma-fork from JXcore. So the happiest solution would be 1 assuming there is some way for us to flag what is going on (e.g. tell the code 'I don't want reuse). But if that turns out to be a serious nightmare then we have no option but go to option 2 and accept a forever fork. :(

**Comment by orangemocha** [comment]
Option 1 should be easy to implement, so there is no need to affect existing functionality. Thanks for the input!

As an implementation note, @enricogior told me that in his current implementation of the secondary single-instance, process.threadId actually has a value greater than 0, so we'll need to either change that or come up with another way to be able to distinguish our secondary instance from a JXcore traditional sub-instance.

**Comment by yaronyg** [comment]
Yeah it seems like having a flag we can submit when we create a second instance whose meaning is "Don't do the shared socket hack" then we would have a flag we could check that would tell us to skip that hack.

**Comment by enricogior** [comment]
I think there are two issues here:
1 - the hack is buggy, a flag to enable or disable it at runtime is OK for the desktop version.
2 - for Thali, we will build a jxcore-cordova version that will only support one restart-able thread, in that case the flag at runtime is kind of wrong, it should be a compile time flag to completely disable the hack since it can't and should never be enabled in that scenario.

**Comment by yaronyg** [comment]
If we build jxcore-cordova version to only support exactly two instances then aren't we effectively forking jxcore-cordova forever? In other words, it's one thing to introduce a new mode to jxcore-cordova that will only support two instances based on some flag but still 'supports' the old behavior. It's another to make jxcore-cordova only support two instances and ban everything else. In the later case aren't we forking?

**Comment by enricogior** [comment]
@yaronyg 
given the resources we currently have, in order to deliver the sub-thread functionality asap, we are going to implement it supporting only the new mode. Once the new mode is fully functional and well tested, we can merge the new mode with the old mode. There are still some areas that we don't know how they will work with the sub-thread (for example, the cordova to jxcore bridge). Trying to add the new mode while keeping the old mode intact is extra work that may prolong the development time. It will be easier to do a merge after we have the new mode fully implemented. Does it sound good?

**Comment by yaronyg** [comment]
Yup. Makes sense. We'll have to ask our paying customer if they want to cough up the cash to prevent a fork. It would be good to make sure that the folks in Poland understand what is going on since they will need to communicate this up the chain on their side.

**Comment by enricogior** [comment]
Fixed: https://github.com/thaliproject/jxcore/commit/9dae3421dde3597164dcfebd16ef76e7c96df118
