### ISSUE TITLE
Regenerate our JXcore version of NPM to not put Shawn's path into the npmrc

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore#9]
When we generate npmjx311 (this lives in jxcore\tools\npmjx) we actually have the path /Users/cicoriasmbp13/ all over the place. This means that folks who use JXcore NPM have to create that literal path in their system. If nothing else that is a possible attack on Windows since it requires creating a directory under Users which is just a bad idea.

I believe this is all being set in deps/npm/lib/config/defaults.js as a result of the value of setting the home variable.

Now the obvious question is - o.k. so what path should it be set too? It's pretty obvious that it wants to be set to the user's local home directory. I'm not sure why this isn't being set automatically. 

I'm probably sending you on a wild goose chase but this smells like a bug in https://github.com/thaliproject/jxcore/blob/master/tools/npmjx/index.js#L156, that function should figure out where the user's local directory is and update the npmrc to change the paths.

Although the more I think about it the more likely I think it is that putting npmrc into the tar.gz is the actual bug. So maybe we just change the packager logic so that file isn't included?

**Comment by yaronyg** [comment]
It looks like the current install is missing some sub-modules. We are trying to figure out the problem.

**Comment by enricogior** [comment]
In our copy of npm there are two sub-module missing:
https://github.com/npm/npm/tree/master/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules

Another file that is missing is the default npmrc.

With those fixes I'm not getting anymore errors when compiling leveldown-mobile.

**Comment by enricogior** [comment]
Fixing the sub-module problem has revealed what it may have caused it in the first place: it's probable that the sub-module wasn't added to the original npm commit because of the path's length, on Windows git seems to not work with paths longer than 140 chars, at least my git installation was still not showing the sub-module as a new item in the repo when I copied the file in their location.
I used a Linux machine to add the sub-module and when on the Windows box I pulled the commit from github I got this error:
```
C:\github\thaliproject\jxcore [master_enrico_763 +3 ~0 -0 !]> git pull thali-jxcore master_enrico_763
remote: Counting objects: 30, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 30 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (30/30), done.
From https://github.com/thaliproject/jxcore
 * branch            master_enrico_763 -> FETCH_HEAD
   3e010df..bd8b3f0  master_enrico_763 -> thali-jxcore/master_enrico_763
m.AllocationBase 0x0, m.BaseAddress 0x68570000, m.RegionSize 0x70000, m.State 0x10000
C:\Users\enrico\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin\tr.exe: *** Couldn't reser
ve space for cygwin's heap (0x68570000 <0x870000>) in child, Win32 error 0
There are no candidates for merging among the refs that you just fetched.
Generally this means that you provided a wildcard refspec which had no
matches on the remote end.
```
We need to understand if it's something specific to my git installation or if all Windows git versions are affected by the same problem.

**Comment by yaronyg** [comment]
There is a problem that GIT on Windows is ignoring some files because the paths are too long. We might just have to cross compile.

**Comment by enricogior** [comment]
I followed your suggestion: upgrading to the latest git version has fixed the problem :)

The next issue is the behavior of npmjx.
On Windows, by default, npm for nodejs uses:
- Users\username\AppData\Roaming\npm-cache
- Users\username\AppData\Roaming\npm
to store its registry and the modules installed with the -g switch.

The path for the global modules can be set in `npmrc` using `prefix=${APPDATA}\npm`.
The default value is set by the installer and changes based on the platform.

In jxcore there are this scripts that uses a jxcore configuration file:
https://github.com/thaliproject/jxcore/blob/master/lib/jx/_jx_config.js
https://github.com/thaliproject/jxcore/blob/master/lib/jx/_jx_install.js
but I haven't found specific documentation about the configuration file and in particular if that configuration file can be used to configure npmjx parameters.

By default, npmjx uses:
- Users\username\AppData\Roaming\npm-cache
for its registry and installs global modules in the folder where jx.exe lives.
That is not a good default behavior.

Another thing we need to fix is setting the environment path to execute commands installed along side with global modules.

**Comment by enricogior** [comment]
In order to properly test the updated npm I would need access to the folder https://jxcore.azureedge.net/npmjx/ to upload the files.

**Comment by yaronyg** [comment]
8, 9 & 763 are all being worked on at the same time. We are guessing that we have at least another day of work, maybe more.

**Comment by yaronyg** [comment]
@enricogior I will need you to provide me with a hotmail or live or other Microsoft hosted email address so I can give that address access to our Azure account.

**Comment by enricogior** [comment]
PR submitted: https://github.com/thaliproject/jxcore/pull/15
Files updated:
 - https://jxcore.blob.core.windows.net/jxcore-release/0312/release/jx_win64v8b.zip
 - https://jxcore.blob.core.windows.net/jxcore-release/npmjx/npmjx311b.tar.gz
 - https://jxcore.blob.core.windows.net/jxcore-release/npmjx/npmjxv311b.jx
